apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logai-data-pvc
  labels:
    app.kubernetes.io/name: logai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Optional: uncomment and specify your storage class if not using the default
  # storageClassName: standard
